rm -rf test/msp430/core/fuse/omsp_and_gate_autogen.sv
rm -rf test/msp430/core/fuse/omsp_clock_gate_autogen.sv
rm -rf test/msp430/core/fuse/omsp_clock_mux_autogen.sv
rm -rf test/msp430/core/fuse/omsp_scan_mux_autogen.sv
rm -rf test/msp430/core/fuse/omsp_sync_cell_autogen.sv
rm -rf test/msp430/core/fuse/omsp_sync_reset_autogen.sv
rm -rf test/msp430/core/fuse/omsp_wakeup_cell_autogen.sv
rm -rf test/msp430/core/main/BCM_autogen.sv
rm -rf test/msp430/core/main/DBG_autogen.sv
rm -rf test/msp430/core/main/EXECUTION_autogen.sv
rm -rf test/msp430/core/main/FRONTEND_autogen.sv
rm -rf test/msp430/core/main/GPIO_autogen.sv
rm -rf test/msp430/core/main/MEMORY_autogen.sv
rm -rf test/msp430/core/main/MULTIPLIER_autogen.sv
rm -rf test/msp430/core/main/SFR_autogen.sv
rm -rf test/msp430/core/main/T_A_autogen.sv
rm -rf test/msp430/core/main/T_WATCOG_autogen.sv
rm -rf test/msp430/core/main/TEMPLATE_08_autogen.sv
rm -rf test/msp430/core/main/TEMPLATE_16_autogen.sv
rm -rf test/msp430/core/main/UART_autogen.sv
rm -rf test/msp430/core/omsp/omsp_alu_autogen.sv
rm -rf test/msp430/core/omsp/omsp_dbg_hwbrk_autogen.sv
rm -rf test/msp430/core/omsp/omsp_dbg_i2c_autogen.sv
rm -rf test/msp430/core/omsp/omsp_dbg_uart_autogen.sv
rm -rf test/msp430/core/omsp/omsp_register_file_autogen.sv

rm -rf test/msp430/core/MSP430_CORE_autogen.sv

rm -rf test/msp430/pkg/openMSP430_defines_autogen.sv
