
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[365] =
    {   0,
        0,    0,   95,   94,   64,   94,   93,   75,   76,   87,
       84,   92,   85,   74,   86,   65,   91,   90,   81,   89,
       82,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   88,    0,    0,    0,   74,   83,   65,   78,   77,
       79,   80,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   21,   22,   25,   74,
       74,   74,   74,   74,   74,   74,   34,   35,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   51,   74,   74,   74,   74,   74,   74,    0,    0,

       74,   67,    0,   63,    0,    0,    0,    1,    2,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   15,   74,
       74,   17,   74,   74,   74,   74,   74,   74,   28,   29,
       74,   31,   32,   74,   74,   37,   74,   74,   74,   74,
       74,   74,   74,   46,   47,   74,   74,   74,   74,   74,
       58,   74,   74,   74,    0,    0,   62,    0,    0,    0,
       74,   74,   74,   74,    7,   74,   74,   74,   74,   13,
       74,   74,   74,   74,   74,   74,   74,   74,   27,   30,
       74,   74,   38,   74,   74,   74,   74,   74,   74,   74,
       50,   74,   74,   74,   56,   74,   74,   60,   61,   66,

        0,    0,    0,    0,   74,    4,    5,    6,   74,   74,
       74,   74,   14,   74,   74,   74,   74,   23,   74,   74,
       33,   74,   74,   41,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,    0,   72,    0,    0,
       74,   74,   74,   74,   74,   12,   16,   74,   74,   74,
       74,   74,   74,   36,   74,   74,   42,   74,   43,   44,
       45,   74,   74,   74,   74,   74,   74,   74,   68,    0,
       73,   74,   74,   74,   74,   74,   74,   74,   74,   20,
       24,   26,   74,   40,   74,   74,   74,   74,   74,   74,
       74,   74,   71,   74,   74,    9,   74,   74,   74,   18,

       19,   74,   74,   74,   74,   74,   74,   74,   57,   59,
       74,    8,   74,   74,   74,   39,   74,   49,   74,   54,
       74,   74,   74,   74,   74,   74,   74,   74,   55,   74,
       74,   74,   74,   74,   74,   69,   74,   74,   53,    3,
       10,   74,   70,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   48,   74,   74,   52,   74,
       74,   74,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    4,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   12,   30,   31,   32,   33,   34,   35,
       12,   36,   37,   38,   39,   40,   41,   42,   43,   44,
        1,    1,    1,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   12,   55,   56,   57,   58,
       59,   60,   12,   61,   62,   63,   64,   65,   66,   67,
       68,   44,    1,   69,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    2,    1,    3,    3,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    3,    2,    3,    2,    3,    3,    3,    3,    3,
        3,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    3,    2,    1
    } ;

static const flex_int16_t yy_base[368] =
    {   0,
        0,    0, 1023, 1024, 1024,   56, 1024, 1024, 1024, 1024,
     1024, 1024, 1011, 1016, 1001,   57, 1000, 1024,  999,  997,
      997,   68,   71,   69,   72,   74,  104,   70,  107,   82,
       76,  113,  140,  103,  146,  200,  155,  137,   73,  156,
      152,  173,  213, 1013,  197, 1009, 1024,   68, 1024, 1024,
     1024, 1024,  151,  188,  229,  192,  201,  183,  234,  185,
      225,  259,  219,  112,  236,  237, 1008,  241, 1007,  227,
      254,  208,  279,  266,  271,  267, 1006, 1005,  273,  276,
      280,  281,  284,  291,  288,  300,  306,  305,  307,  297,
      322,  108,  313,  314,  330,  301,  339,  315,    0,  334,

      338, 1024, 1007, 1006,   49,  327,  328, 1002, 1001,  340,
      362,  374,  364,  361,  325,  370,  376,  389, 1000,  386,
      366,  999,  383,  391,  387,  395,  393,  412,  998,  997,
      397,  996,  989,  396,  399,  988,  400,  414,  428,  418,
      431,  425,  420,  984,  983,  149,  437,  454,  439,  461,
      982,  463,  443,  451,  462,  481,  981,  444,  448,  444,
      468,  483,  472,  482,  980,  493,  495,  497,  498,  978,
      502,  505,  506,  509,  504,  518,  514,  508,  977,  976,
       75,  519,  974,  520,  534,  527,  515,  539,  564,  544,
      972,  559,  566,  569,  970,  571,  562,  968,  967, 1024,

      524,  540,  559,  562,  574,  966,  963,  959,  572,  586,
      589,  588,  958,  591,  592,  604,  619,  957,  594,  616,
     1024,  601,  630,  955,  608,  626,  611,  631,  637,  623,
      634,  641,  640,  651,  650,  676,  622, 1024,  631,  632,
      666,  671,  670,  679,  694,  953,  951,  675,  685,  695,
      699,  700,  696,  947,  701,  704,  942,  705,  938,  936,
      935,  702,  706,  709,  712,  719,  710,  715, 1024,  698,
     1024,  729,  720,  725,  744,  750,  740,  754,  764,  855,
      790,  733,  757,  713,  765,  767,  770,  775,  771,  774,
      778,  779, 1024,  781,  786,  596,  798,  787,  803,  533,

      529,  806,  789,  793,  812,  815,  828,  776,  456,  453,
      801,  408,  830,  805,  842,  344,  840,  838,  837,  197,
      841,  846,  845,  847,  853,  849,  854,  863,  176,  870,
      864,  869,  872,  858,  884,  175,  895,  881,  144,  141,
       88,  873,   86,  894,  900,  906,  885,  909,  879,  902,
      911,  925,  917,  910,  926,   83,  930,  932,   81,  921,
      933,  934,   80, 1024,  994,  997,   81
    } ;

static const flex_int16_t yy_def[368] =
    {   0,
      364,    1,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  365,  364,  364,  364,  364,  364,  364,
      364,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  364,  364,  366,  364,  365,  364,  364,  364,  364,
      364,  364,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  367,  367,

      365,  364,  366,  364,  364,  364,  364,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  367,  367,  365,  364,  364,  364,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  364,

      364,  364,  364,  364,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      364,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  364,  364,  364,  364,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  364,  364,
      364,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  364,  365,  365,  365,  365,  365,  365,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,    0,  364,  364,  364
    } ;

static const flex_int16_t yy_nxt[1094] =
    {   0,
        4,    5,    6,    7,    6,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   14,   29,   14,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   14,   14,   14,   22,   23,   24,   25,   26,
       27,   28,   14,   29,   14,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   14,   42,   43,
       48,   48,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   48,   48,  155,   45,   45,   45,   45,  158,   58,
       45,  221,   45,   96,   66,   56,   72,   43,   53,   43,

       54,   57,   59,   55,   61,   60,   62,   45,   45,   73,
       70,   45,   45,  158,   58,   71,   45,   45,   96,   66,
       56,   72,   43,   53,   63,   54,   57,   59,   55,   61,
       60,   62,   67,   74,   73,   70,   81,   64,   82,   68,
       71,   45,   65,   69,   45,   45,   75,  122,   45,   63,
       45,   76,  148,   45,   99,   45,  100,   67,   74,   45,
       45,   81,   64,   82,   68,   77,   83,   65,   69,   94,
       84,   75,  122,   95,   85,   78,   76,   79,   80,   45,
       45,  108,   91,   97,   98,  101,   43,   45,   92,   45,
       77,   83,   45,  190,   94,   84,   45,   93,   95,   85,

       78,   45,   79,   80,   45,   45,  108,   91,   97,   98,
      101,  109,   45,   92,   43,  102,   43,  102,  112,  114,
       99,  105,   93,   45,   86,  117,   43,  106,   87,   45,
       88,   45,  107,   45,  113,   89,  109,   90,   45,   43,
       45,   45,  129,  112,  114,   45,  105,  121,  127,   86,
      117,  110,  106,   87,   43,   88,   43,  107,   45,  113,
       89,  118,   90,   45,  111,  115,  116,  129,  123,  124,
       45,   45,  121,  127,  125,   45,  110,   45,  126,   43,
       45,  102,  119,   45,   45,   45,  118,  128,   45,  111,
      115,  116,   45,  123,  124,   45,  120,  134,  131,  125,

      135,   45,  130,  126,   45,   45,  132,  119,  133,   45,
       45,   45,  128,  136,  138,  137,  139,   45,   45,   45,
      146,  120,  134,  131,  141,  135,   45,  130,  140,   45,
      142,  132,  143,  133,   45,  144,  152,  145,  136,  138,
      137,  139,   45,   45,   45,  146,  147,  149,   45,  141,
      150,  159,  154,  140,  151,  142,  160,  143,  156,  166,
      144,  152,  145,  153,  106,   45,   45,  161,   45,  107,
       45,  147,  149,  157,   45,  150,  159,  154,   45,  151,
       45,  160,  162,  156,  166,  165,  164,   45,  153,  106,
       45,   45,  161,   45,  107,   45,  173,   45,  157,   45,

       45,   45,  163,   45,   45,  174,  167,  162,  169,  168,
      165,  164,   45,  170,  172,  175,   45,  171,   45,  177,
      180,  173,   45,  182,   45,  176,  181,  163,  178,   45,
      174,  167,   45,  169,  168,   45,  184,  183,  170,  172,
      175,   45,  171,   45,  177,  180,  179,   45,  182,  188,
      176,  181,  189,  178,  185,   45,  186,   45,   45,  187,
       45,  184,  183,  195,  200,   45,  200,   45,  201,  191,
      204,  179,   45,  202,  188,  198,   45,  189,  199,  185,
      203,  186,  192,  200,  187,  200,   45,   45,  195,  196,
      193,  197,  194,  201,  191,  204,  205,   45,  202,   45,

      198,   45,   45,  199,  207,  203,   45,  192,   45,   45,
       45,  208,   45,   45,  196,  193,  197,  194,   45,   45,
      158,  205,   45,   45,   45,  206,  209,  213,  220,  207,
      200,   45,  210,   45,  215,  212,  208,   45,   45,  217,
      219,  211,  214,   45,  223,  158,  216,  226,   45,  200,
      206,  209,  213,  220,  222,  218,  237,  210,  224,  215,
      212,  227,  225,   45,  217,  219,   45,  214,   45,  223,
       45,  216,  226,   45,  230,   45,   45,  238,   45,  222,
      218,  237,  236,  224,  228,  239,  227,  225,  229,  240,
       45,  231,   45,   45,  232,   45,   45,  235,   45,  230,

       45,  234,  238,  233,  242,   45,  243,  236,   45,  228,
      239,  241,   45,  229,  240,   45,  231,  244,  252,  232,
       45,  246,  235,   45,  248,  245,  234,   45,  233,  242,
       45,  243,  249,  247,   45,   45,  241,  254,   45,  250,
      257,   45,  244,  252,   45,   45,  246,  251,  259,  248,
      245,  253,  258,  255,   45,   45,  262,  249,  247,  269,
      261,  260,  254,  265,  250,  257,  256,  264,  270,  271,
       45,  263,  251,  259,   45,   45,  253,  258,  255,   45,
       45,  262,  267,   45,  269,  261,  260,  266,  265,   45,
      272,  256,  264,  270,  271,  273,  263,  268,   45,   45,

       45,  277,  274,   45,   45,   45,   45,  267,   45,   45,
       45,  275,  266,   45,   45,  272,   45,   45,  278,   45,
      273,  280,  268,   45,   45,  293,  277,  274,  286,   45,
      287,  276,  279,   45,  291,  281,  275,   45,  282,  283,
      284,  288,  289,  278,   45,  292,  280,  290,   45,  285,
      293,  294,  295,  286,   45,  287,  276,  279,   45,  291,
      281,   45,  296,  282,  283,  284,  288,  289,   45,   45,
      292,   45,  290,  298,   45,   45,  294,  295,   45,   45,
       45,  297,   45,   45,  299,   45,  300,  296,  301,  303,
       45,   45,  302,   45,   45,  304,  305,   45,  298,  306,

      308,  309,   45,  310,  307,   45,  297,   45,  322,   45,
       45,  300,  317,  301,  303,  318,   45,  302,  311,   45,
      304,  305,  313,  312,  306,  308,  309,  315,  310,  307,
      316,  314,   45,  322,   45,  325,  319,  317,  320,  323,
      318,   45,   45,  311,   45,   45,   45,  313,  312,   45,
       45,   45,  315,   45,  321,  316,  324,   45,   45,   45,
      325,  319,   45,  320,  323,  326,  327,   45,   45,  330,
      331,  333,  329,   45,   45,  335,   45,   45,  336,  321,
      332,  324,  328,   45,  342,   45,  334,  339,   45,   45,
      326,  327,  338,  340,  330,  331,  333,  329,   45,   45,

      335,  346,  337,  336,   45,  332,   45,  341,  343,  342,
       45,  334,  339,   45,   45,   45,  347,  338,  340,  344,
      345,   45,  350,  352,  348,   45,  346,  337,  349,   45,
       45,  351,  341,  343,   45,  353,   45,   45,   45,   45,
       45,  347,   45,  357,  344,  345,   45,  350,  354,  348,
      358,   45,  356,  349,  360,   45,  351,   45,  361,   45,
      353,   45,   45,   45,  355,  359,  362,   45,  357,  363,
       45,   45,   45,  354,   45,  358,   45,  356,   45,  360,
       45,   45,   45,  361,   45,   45,   45,   45,   45,  355,
      359,  362,   45,   45,  363,   46,   46,  103,  103,  103,

       45,   45,   45,   45,   45,   45,   45,  104,  104,   45,
       45,   45,   45,   45,  104,   52,   51,   50,   49,   47,
       45,   44,  364,    3,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364

    } ;

static const flex_int16_t yy_chk[1094] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    6,
       16,   16,   22,   24,   28,   23,   25,   39,   26,  181,
       31,   48,   48,  367,  363,  359,   30,  356,  105,   24,
      343,  181,  341,   39,   28,   23,   31,    6,   22,    6,

       22,   23,   24,   22,   26,   25,   26,   34,   27,   31,
       30,   29,   92,  105,   24,   30,   64,   32,   39,   28,
       23,   31,    6,   22,   27,   22,   23,   24,   22,   26,
       25,   26,   29,   32,   31,   30,   34,   27,   34,   29,
       30,   38,   27,   29,   33,  340,   32,   64,  339,   27,
       35,   32,   92,  146,   41,   53,   41,   29,   32,   37,
       40,   34,   27,   34,   29,   33,   35,   27,   29,   38,
       35,   32,   64,   38,   35,   33,   32,   33,   33,  336,
      329,   53,   37,   40,   40,   41,   42,   58,   37,   60,
       33,   35,   54,  146,   38,   35,   56,   37,   38,   35,

       33,  320,   33,   33,   36,   57,   53,   37,   40,   40,
       41,   54,   72,   37,   42,   43,   42,   43,   56,   58,
       41,   45,   37,   63,   36,   60,   43,   45,   36,   61,
       36,   70,   45,   55,   57,   36,   54,   36,   59,   42,
       65,   66,   72,   56,   58,   68,   45,   63,   70,   36,
       60,   55,   45,   36,   43,   36,   43,   45,   71,   57,
       36,   61,   36,   62,   55,   59,   59,   72,   65,   66,
       74,   76,   63,   70,   68,   75,   55,   79,   68,   43,
       80,   43,   62,   73,   81,   82,   61,   71,   83,   55,
       59,   59,   85,   65,   66,   84,   62,   76,   74,   68,

       79,   90,   73,   68,   86,   96,   75,   62,   75,   88,
       87,   89,   71,   80,   82,   81,   83,   93,   94,   98,
       90,   62,   76,   74,   85,   79,   91,   73,   84,  115,
       86,   75,   87,   75,   95,   88,   96,   89,   80,   82,
       81,   83,  101,   97,  110,   90,   91,   93,  316,   85,
       94,  106,   98,   84,   95,   86,  107,   87,  100,  115,
       88,   96,   89,   97,  100,  114,  111,  110,  113,  100,
      121,   91,   93,  101,  116,   94,  106,   98,  112,   95,
      117,  107,  111,  100,  115,  114,  113,  123,   97,  100,
      120,  125,  110,  118,  100,  124,  121,  127,  101,  126,

      134,  131,  112,  135,  137,  123,  116,  111,  117,  116,
      114,  113,  312,  118,  120,  124,  128,  118,  138,  126,
      131,  121,  140,  135,  143,  125,  134,  112,  127,  142,
      123,  116,  139,  117,  116,  141,  138,  137,  118,  120,
      124,  147,  118,  149,  126,  131,  128,  153,  135,  142,
      125,  134,  143,  127,  139,  154,  140,  310,  148,  141,
      309,  138,  137,  149,  155,  150,  155,  152,  158,  147,
      160,  128,  161,  159,  142,  153,  163,  143,  154,  139,
      159,  140,  148,  156,  141,  156,  164,  162,  149,  150,
      148,  152,  148,  158,  147,  160,  161,  166,  159,  167,

      153,  168,  169,  154,  163,  159,  171,  148,  175,  172,
      173,  164,  178,  174,  150,  148,  152,  148,  177,  187,
      156,  161,  176,  182,  184,  162,  166,  171,  178,  163,
      155,  186,  167,  301,  173,  169,  164,  300,  185,  175,
      177,  168,  172,  188,  184,  156,  174,  187,  190,  156,
      162,  166,  171,  178,  182,  176,  201,  167,  185,  173,
      169,  188,  186,  192,  175,  177,  197,  172,  189,  184,
      193,  174,  187,  194,  190,  196,  209,  202,  205,  182,
      176,  201,  197,  185,  189,  203,  188,  186,  189,  204,
      210,  192,  212,  211,  193,  214,  215,  196,  219,  190,

      296,  194,  202,  193,  209,  222,  210,  197,  216,  189,
      203,  205,  225,  189,  204,  227,  192,  211,  219,  193,
      220,  212,  196,  217,  215,  211,  194,  230,  193,  209,
      226,  210,  216,  214,  223,  228,  205,  222,  231,  217,
      225,  229,  211,  219,  233,  232,  212,  217,  227,  215,
      211,  220,  226,  223,  235,  234,  230,  216,  214,  237,
      229,  228,  222,  233,  217,  225,  223,  232,  239,  240,
      241,  231,  217,  227,  243,  242,  220,  226,  223,  248,
      236,  230,  235,  244,  237,  229,  228,  234,  233,  249,
      241,  223,  232,  239,  240,  242,  231,  236,  245,  250,

      253,  248,  243,  251,  252,  255,  262,  235,  256,  258,
      263,  244,  234,  264,  267,  241,  265,  284,  249,  268,
      242,  251,  236,  266,  273,  270,  248,  243,  262,  274,
      263,  245,  250,  272,  267,  252,  244,  282,  253,  255,
      256,  264,  265,  249,  277,  268,  251,  266,  275,  258,
      270,  272,  273,  262,  276,  263,  245,  250,  278,  267,
      252,  283,  274,  253,  255,  256,  264,  265,  279,  285,
      268,  286,  266,  276,  287,  289,  272,  273,  290,  288,
      308,  275,  291,  292,  277,  294,  278,  274,  279,  285,
      295,  298,  283,  303,  281,  286,  287,  304,  276,  288,

      290,  291,  297,  292,  289,  311,  275,  299,  308,  314,
      302,  278,  303,  279,  285,  304,  305,  283,  294,  306,
      286,  287,  297,  295,  288,  290,  291,  299,  292,  289,
      302,  298,  307,  308,  313,  314,  305,  303,  306,  311,
      304,  319,  318,  294,  317,  321,  315,  297,  295,  323,
      322,  324,  299,  326,  307,  302,  313,  325,  327,  280,
      314,  305,  334,  306,  311,  315,  317,  328,  331,  321,
      322,  324,  319,  332,  330,  326,  333,  342,  327,  307,
      323,  313,  318,  349,  334,  338,  325,  331,  335,  347,
      315,  317,  330,  332,  321,  322,  324,  319,  344,  337,

      326,  342,  328,  327,  345,  323,  350,  333,  335,  334,
      346,  325,  331,  348,  354,  351,  344,  330,  332,  337,
      338,  353,  347,  349,  345,  360,  342,  328,  346,  352,
      355,  348,  333,  335,  357,  350,  358,  361,  362,  261,
      260,  344,  259,  354,  337,  338,  257,  347,  351,  345,
      355,  254,  353,  346,  358,  247,  348,  246,  360,  224,
      350,  218,  213,  208,  352,  357,  361,  207,  354,  362,
      206,  199,  198,  351,  195,  355,  191,  353,  183,  358,
      180,  179,  170,  360,  165,  157,  151,  145,  144,  352,
      357,  361,  136,  133,  362,  365,  365,  366,  366,  366,

      132,  130,  129,  122,  119,  109,  108,  104,  103,   78,
       77,   69,   67,   46,   44,   21,   20,   19,   17,   15,
       14,   13,    3,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "vhdllex.l"
#line 2 "vhdllex.l"
////////////////////////////////////////////////////////////////////////////////
//                                            __ _      _     _               //
//                                           / _(_)    | |   | |              //
//                __ _ _   _  ___  ___ _ __ | |_ _  ___| | __| |              //
//               / _` | | | |/ _ \/ _ \ '_ \|  _| |/ _ \ |/ _` |              //
//              | (_| | |_| |  __/  __/ | | | | | |  __/ | (_| |              //
//               \__, |\__,_|\___|\___|_| |_|_| |_|\___|_|\__,_|              //
//                  | |                                                       //
//                  |_|                                                       //
//                                                                            //
//                                                                            //
//              VHDL to Verilog                                               //
//              HDL Translator                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Copyright (c) 202X-202X by the author(s)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * =============================================================================
 * Author(s):
 *   Francisco Javier Reina Campo <frareicam@gmail.com>
 *   yunkun yang <yangyk16@whu.edu.cn>
 */

#include "vhd2sv.h"

int yylexlinenum;
int yywrap(void)
{
  return (1);
}

#line 855 "lex.yy.c"
#line 856 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 53 "vhdllex.l"

#line 1075 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 365 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1024 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 54 "vhdllex.l"
{yylval = MallocTcell(T_ALL, NULLSTR, yylexlinenum); return(T_ALL);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 55 "vhdllex.l"
{yylval = MallocTcell(T_AND, NULLSTR, yylexlinenum); return(T_AND);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "vhdllex.l"
{yylval = MallocTcell(T_ARCHITECTURE, NULLSTR, yylexlinenum); return(T_ARCHITECTURE);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "vhdllex.l"
{yylval = MallocTcell(T_ARRAY, NULLSTR, yylexlinenum); return(T_ARRAY);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "vhdllex.l"
{yylval = MallocTcell(T_BEGIN, NULLSTR, yylexlinenum); return(T_BEGIN);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "vhdllex.l"
{yylval = MallocTcell(T_BLOCK, NULLSTR, yylexlinenum); return(T_BLOCK);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "vhdllex.l"
{yylval = MallocTcell(T_CASE, NULLSTR, yylexlinenum); return(T_CASE);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "vhdllex.l"
{yylval = MallocTcell(T_COMPONENT, NULLSTR, yylexlinenum); return(T_COMPONENT);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "vhdllex.l"
{yylval = MallocTcell(T_CONSTANT, NULLSTR, yylexlinenum); return(T_CONSTANT);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "vhdllex.l"
{yylval = MallocTcell(T_CONVINT, NULLSTR, yylexlinenum); return(T_CONVINT);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "vhdllex.l"
{yylval = MallocTcell(T_CONVSTDVEC, NULLSTR, yylexlinenum); return(T_CONVSTDVEC);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "vhdllex.l"
{yylval = MallocTcell(T_DOWNTO, NULLSTR, yylexlinenum); return(T_DOWNTO);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "vhdllex.l"
{yylval = MallocTcell(T_ELSE, NULLSTR, yylexlinenum); return(T_ELSE);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "vhdllex.l"
{yylval = MallocTcell(T_ELSIF, NULLSTR, yylexlinenum); return(T_ELSIF);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "vhdllex.l"
{yylval = MallocTcell(T_END, NULLSTR, yylexlinenum); return(T_END);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "vhdllex.l"
{yylval = MallocTcell(T_ENTITY, NULLSTR, yylexlinenum); return(T_ENTITY);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "vhdllex.l"
{yylval = MallocTcell(T_FOR, NULLSTR, yylexlinenum); return(T_FOR);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "vhdllex.l"
{yylval = MallocTcell(T_FUNCTION, NULLSTR, yylexlinenum); return(T_FUNCTION);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "vhdllex.l"
{yylval = MallocTcell(T_GENERATE, NULLSTR, yylexlinenum); return(T_GENERATE);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "vhdllex.l"
{yylval = MallocTcell(T_GENERIC, NULLSTR, yylexlinenum); return(T_GENERIC);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "vhdllex.l"
{yylval = MallocTcell(T_IF, NULLSTR, yylexlinenum); return(T_IF);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "vhdllex.l"
{yylval = MallocTcell(T_IN, NULLSTR, yylexlinenum); return(T_IN);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "vhdllex.l"
{yylval = MallocTcell(T_INOUT, NULLSTR, yylexlinenum); return(T_INOUT);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "vhdllex.l"
{yylval = MallocTcell(T_INTEGER, NULLSTR, yylexlinenum); return(T_INTEGER);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "vhdllex.l"
{yylval = MallocTcell(T_IS, NULLSTR, yylexlinenum); return(T_IS);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "vhdllex.l"
{yylval = MallocTcell(T_LIBRARY, NULLSTR, yylexlinenum); return(T_LIBRARY);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "vhdllex.l"
{yylval = MallocTcell(T_LOOP, NULLSTR, yylexlinenum); return(T_LOOP);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "vhdllex.l"
{yylval = MallocTcell(T_MAP, NULLSTR, yylexlinenum); return(T_MAP);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "vhdllex.l"
{yylval = MallocTcell(T_MOD, NULLSTR, yylexlinenum); return(T_MOD);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "vhdllex.l"
{yylval = MallocTcell(T_NAND, NULLSTR, yylexlinenum); return(T_NAND);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "vhdllex.l"
{yylval = MallocTcell(T_NOR, NULLSTR, yylexlinenum); return(T_NOR);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "vhdllex.l"
{yylval = MallocTcell(T_NOT, NULLSTR, yylexlinenum); return(T_NOT);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "vhdllex.l"
{ /* NO ACTION */ }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "vhdllex.l"
{yylval = MallocTcell(T_OF, NULLSTR, yylexlinenum); return(T_OF);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "vhdllex.l"
{yylval = MallocTcell(T_OR, NULLSTR, yylexlinenum); return(T_OR);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "vhdllex.l"
{yylval = MallocTcell(T_OTHERS, NULLSTR, yylexlinenum); return(T_OTHERS);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "vhdllex.l"
{yylval = MallocTcell(T_OUT, NULLSTR, yylexlinenum); return(T_OUT);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "vhdllex.l"
{yylval = MallocTcell(T_PORT, NULLSTR, yylexlinenum); return(T_PORT);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "vhdllex.l"
{yylval = MallocTcell(T_PROCEDURE, NULLSTR, yylexlinenum); return(T_PROCEDURE);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 93 "vhdllex.l"
{yylval = MallocTcell(T_PROCESS, NULLSTR, yylexlinenum); return(T_PROCESS);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 94 "vhdllex.l"
{yylval = MallocTcell(T_RANGE, NULLSTR, yylexlinenum); return(T_RANGE);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 95 "vhdllex.l"
{yylval = MallocTcell(T_RETURN, NULLSTR, yylexlinenum); return(T_RETURN);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "vhdllex.l"
{yylval = MallocTcell(T_SELECT, NULLSTR, yylexlinenum); return(T_SELECT);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 97 "vhdllex.l"
{yylval = MallocTcell(T_SIGNAL, NULLSTR, yylexlinenum); return(T_SIGNAL);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 98 "vhdllex.l"
{yylval = MallocTcell(T_SIGNED, NULLSTR, yylexlinenum); return(T_SIGNED);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "vhdllex.l"
{yylval = MallocTcell(T_SLL, NULLSTR, yylexlinenum); return(T_SLL);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "vhdllex.l"
{yylval = MallocTcell(T_SRL, NULLSTR, yylexlinenum); return(T_SRL);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "vhdllex.l"
{yylval = MallocTcell(T_STDLOGICVEC, NULLSTR, yylexlinenum); return(T_STDLOGICVEC);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "vhdllex.l"
{yylval = MallocTcell(T_STDLOGIC, NULLSTR, yylexlinenum); return(T_STDLOGIC);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "vhdllex.l"
{yylval = MallocTcell(T_THEN, NULLSTR, yylexlinenum); return(T_THEN);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "vhdllex.l"
{yylval = MallocTcell(T_TO, NULLSTR, yylexlinenum); return(T_TO);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "vhdllex.l"
{yylval = MallocTcell(T_TOSTDLOGICVEC, NULLSTR, yylexlinenum); return(T_TOSTDLOGICVEC);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "vhdllex.l"
{yylval = MallocTcell(T_TOUNSIGNED, NULLSTR, yylexlinenum); return(T_TOUNSIGNED);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "vhdllex.l"
{yylval = MallocTcell(T_TOSIGNED, NULLSTR, yylexlinenum); return(T_TOSIGNED);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "vhdllex.l"
{yylval = MallocTcell(T_TOINTEGER, NULLSTR, yylexlinenum); return(T_TOINTEGER);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "vhdllex.l"
{yylval = MallocTcell(T_TYPE, NULLSTR, yylexlinenum); return(T_TYPE);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "vhdllex.l"
{yylval = MallocTcell(T_UNSIGNED, NULLSTR, yylexlinenum); return(T_UNSIGNED);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "vhdllex.l"
{yylval = MallocTcell(T_USE, NULLSTR, yylexlinenum); return(T_USE);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "vhdllex.l"
{yylval = MallocTcell(T_VARIABLE, NULLSTR, yylexlinenum); return(T_VARIABLE);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "vhdllex.l"
{yylval = MallocTcell(T_WHEN, NULLSTR, yylexlinenum); return(T_WHEN);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "vhdllex.l"
{yylval = MallocTcell(T_WITH, NULLSTR, yylexlinenum); return(T_WITH);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "vhdllex.l"
{yylval = MallocTcell(T_XOR, NULLSTR, yylexlinenum); return(T_XOR);}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 116 "vhdllex.l"
{ RegisterComment(CommentListTop, yytext, &yylexlinenum); }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 117 "vhdllex.l"
{ yylexlinenum++; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 118 "vhdllex.l"
{yylval = MallocTcell(T_DECDIGIT, yytext, yylexlinenum); return(T_DECDIGIT);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 119 "vhdllex.l"
{yylval = MallocTcell(T_HEXDIGIT, yytext, yylexlinenum); return(T_HEXDIGIT);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 120 "vhdllex.l"
{yylval = MallocTcell(T_BINDIGIT, yytext, yylexlinenum); return(T_BINDIGIT);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 121 "vhdllex.l"
{yylval = MallocTcell(T_EVENT, yytext, yylexlinenum); return(T_EVENT);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 122 "vhdllex.l"
{yylval = MallocTcell(T_CLK_POS, yytext, yylexlinenum); return(T_CLK_POS);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 123 "vhdllex.l"
{yylval = MallocTcell(T_CLK_NEG, yytext, yylexlinenum); return(T_CLK_NEG);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 124 "vhdllex.l"
{yylval = MallocTcell(T_ATTR_LENGTH, NULLSTR, yylexlinenum); return(T_ATTR_LENGTH);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 125 "vhdllex.l"
{yylval = MallocTcell(T_ATTR_LEFT, NULLSTR, yylexlinenum); return(T_ATTR_LEFT);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "vhdllex.l"
{yylval = MallocTcell(T_ATTR_RIGHT, NULLSTR, yylexlinenum); return(T_ATTR_RIGHT);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 127 "vhdllex.l"
{yylval = MallocTcell(T_ID, yytext, yylexlinenum); return(T_ID);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 128 "vhdllex.l"
{yylval = MallocTcell(T_LPAREN, NULLSTR, yylexlinenum); return(T_LPAREN);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 129 "vhdllex.l"
{yylval = MallocTcell(T_RPAREN, NULLSTR, yylexlinenum); return(T_RPAREN);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "vhdllex.l"
{yylval = MallocTcell(T_SIGSUBST, NULLSTR, yylexlinenum); return(T_SIGSUBST);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "vhdllex.l"
{yylval = MallocTcell(T_VARSUBST, NULLSTR, yylexlinenum); return(T_VARSUBST);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "vhdllex.l"
{yylval = MallocTcell(T_PARSUBST, NULLSTR, yylexlinenum); return(T_PARSUBST);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "vhdllex.l"
{yylval = MallocTcell(T_LE, NULLSTR, yylexlinenum); return(T_LE);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "vhdllex.l"
{yylval = MallocTcell(T_GT, NULLSTR, yylexlinenum); return(T_GT);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "vhdllex.l"
{yylval = MallocTcell(T_LS, NULLSTR, yylexlinenum); return(T_LS);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "vhdllex.l"
{yylval = MallocTcell(T_NOTEQUAL, NULLSTR, yylexlinenum); return(T_NOTEQUAL);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "vhdllex.l"
{yylval = MallocTcell(T_PLUS, NULLSTR, yylexlinenum); return(T_PLUS);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 138 "vhdllex.l"
{yylval = MallocTcell(T_MINUS, NULLSTR, yylexlinenum); return(T_MINUS);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 139 "vhdllex.l"
{yylval = MallocTcell(T_DIV, NULLSTR, yylexlinenum); return(T_DIV);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "vhdllex.l"
{yylval = MallocTcell(T_MULT, NULLSTR, yylexlinenum); return(T_MULT);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "vhdllex.l"
{yylval = MallocTcell(T_COND_OR, NULLSTR, yylexlinenum); return(T_COND_OR);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "vhdllex.l"
{yylval = MallocTcell(T_EQUAL, NULLSTR, yylexlinenum); return(T_EQUAL);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "vhdllex.l"
{yylval = MallocTcell(T_SEMICOLON, NULLSTR, yylexlinenum); return(T_SEMICOLON);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "vhdllex.l"
{yylval = MallocTcell(T_COLON, NULLSTR, yylexlinenum); return(T_COLON);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "vhdllex.l"
{yylval = MallocTcell(T_COMMA, NULLSTR, yylexlinenum); return(T_COMMA);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "vhdllex.l"
{yylval = MallocTcell(T_CONCAT, NULLSTR, yylexlinenum); return(T_CONCAT);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "vhdllex.l"
ECHO;
	YY_BREAK
#line 1604 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 365 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 365 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 364);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 147 "vhdllex.l"


//\n[\n]+                         { RegisterComment(CommentListTop, yytext, &yylexlinenum); }
// end of file

